### ISSUE TITLE
warnings in package prevent playground builds

### ISSUE THREAD

**Issue by liquidsmok3** [twostraws/Vortex#14]
VortexSystem-Behavior.swift
var adjustedAttractionStrength = attractionStrength / 1000 

The above variable in the listed swift file produces a warning "Variable 'adjustedAttractionStrength' was never mutated; consider changing to a 'let' constant.

This warning only shows up on playgrounds on iPad and unlike Xcode this warning produces a failed build.  And since the error is inside a package I cant change the var to a let.  There may even be more of these warnings but i currently only see one, but it prevents successful builds.

no issues on desktop but im trying to move a project from the desktop to ipad for more flexibility.

**Comment by twostraws** [comment]
This is resolved now – thank you!
