### ISSUE TITLE
Warnings in complete concurrency checking

### ISSUE THREAD

**Issue by Jerry23011** [twostraws/Vortex#18]
Hi, thank you for the awesome library.

I encountered some issues with complete concurrency checking. For example, using the sample app, Xcode gives the warning `"Class property 'confetti' is not concurrency-safe because it is not either conforming to 'Sendable' or isolated to a global actor; this is an error in Swift 6"`

I'm getting my project ready for Swift 6 and tried `@preconcurrency` and `@MainActor`. I'm wondering if there's any way to resolve the issue.

**Comment by twostraws** [comment]
That's odd! I just tried it using the Sandbox project and didn't get any warnings at all. I enabled Swift Language Version 6 for both the project and target, and also enabled all the upcoming features. I guess I'm missing something?

**Comment by Jerry23011** [comment]
I updated to Xcode 16 beta 4 and Swift 6 seems to be working!

Could be a bug in the previous betas and Xcode 15.

**Comment by twostraws** [comment]
Are you okay if we close this issue?

**Comment by Jerry23011** [comment]
Yes of course, thank you :)
