### ISSUE TITLE
Can't add package into the progect

### ISSUE THREAD

**Issue by vitaly-grinchik** [twostraws/Vortex#2]
Hello! 
First Vortex looks great! I tried to use it but couldn't finally. An error occurs on adding it to the project. Please look at pictures enclosed.
Xcode Version 14.2 (14C18)
Target iOS 16.2
MacOS 12.7.2. Monterey

![Vortex-Error-On-Adding](https://github.com/twostraws/Vortex/assets/118172851/0a66bdcb-740c-444f-b073-7586cb6644f9)
![Vortex-Error-Xcode](https://github.com/twostraws/Vortex/assets/118172851/cf63a458-0830-4097-a9e3-2862b32745b0)

**Comment by twostraws** [comment]
Your Xcode version is too old. Although you can target older versions of macOS, I'm not able to support older versions of Swift.

**Comment by vitaly-grinchik** [comment]
Ok, Thanks! I was supposing that reason. Anyway thank your for your great job! Will try it on my ne Mac obligatory!
