### ISSUE TITLE
How to get the same fireworks display?

### ISSUE THREAD

**Issue by ToddHoff** [twostraws/Vortex#6]
Hi,

First, your daughter did a great job. And thanks for the talk.

When I used fireworks, mine didn't look like yours at all. Yet when I pull down the Sandbox project and run your examples, they look correct. The same code in my Xcode project looks rather anemic. I attached a screenshot. I poked around the project but didn't find anything obvious. Any ideas?

Thanks

  VortexView(.fireworks.makeUniqueCopy()) {
            Circle()
                .fill(.white)
                .frame(width: 32)
                .blur(radius: 5)
                .blendMode(.plusLighter)
                .tag("circle")
        }

<img width="336" alt="Screenshot 2024-02-15 at 7 03 06 PM" src="https://github.com/twostraws/Vortex/assets/1286318/eab9a41a-a3ab-403f-87d0-7c196a4d72f9">

**Comment by twostraws** [comment]
Is it perhaps the problem that fireworks rarely work well during daytime? That is, does the fact effect look better in night mode? 🙂

**Comment by ToddHoff** [comment]
LOL

And damn, you are right. Night mode was it.

thanks

**Comment by twostraws** [comment]
Awesome! A nice and easy one to close 🙂
