### ISSUE TITLE
Documentation: Reference to birth rate below 0.0 should probable be below 1.0

### ISSUE THREAD

**Issue by eoinnorris** [twostraws/Vortex#7]
In the VortexSystem description of  birthRate it says that the values can be below zero, but the text implies that this really means between 0.0 and 1.0.

One example ( there are 3)

```
 /// How many particles are created every second. You can use values below 0 here, e.g
    /// a birth rate of 0.2 means one particle being created every 5 seconds.
    public var birthRate: Double
```

**Comment by twostraws** [comment]
You're quite correct – please do open a PR with the fix, if you're comfortable! 🙌

**Comment by eoinnorris** [comment]
PR is here:

https://github.com/twostraws/Vortex/pull/8

**Comment by twostraws** [comment]
Thank you!
