### ISSUE TITLE
Add modifiers for the presets.

### ISSUE THREAD

**Issue by eoinnorris** [twostraws/Vortex#9]
I am playing around with this and it's great. What I would like to do is add modifications to the presets, without recreating the presets. I already have a  VortexView(.storm) which is a copy and paste of the rain modifier with new values but this can get tedious. 

My suggestion:

As a utility function we could add a version of makeUniqueCopy() that takes in all the parameters. This will be private. 

example:

`private func modifyUniqueCopy(tags:[String]? = nil,....)
`

The ... is to indicate that we fill all the potential values here  in not that it is variadic.  If a value is nil it is ignored and we copy from the existing values. If not it replaces the existing values.

Then specific public functions can be named appropriately. 

example

```
 private func copyAndModifyRain( birthRate: Double? = nil,, 
            lifespan: Double? = nil,,
            speed: Double? = nil,,
            speedVariation: Double? = nil,
            angle:Angle? = nil,
            colors: ColorMode? = nil
            size: Double? = nil,
            sizeVariation: Double? = nil,
            stretchFactor: Double? = nil
)
```

Anything not added picks up the default, so you could do a storm like this

```
struct StormView: View {
let windDirection:Angle
let rainType:RainType
    var body: some View {
        VortexView(.rain. copyAndModifyRain(birthRate: RainType.type.storm.rawvalue, angle: windDirection) {
            Circle()
                .fill(.white)
                .frame(width: 32)
                .tag("circle")
        }
    }
}

```

Another alternative is to pass in modifiers in some cases i.e a birthrate modifier rather than an actual value.

This may be better in the application layer, however, as the copyAndModiftyRain can't just be limited to the rain modifier and going all of them would be tedious. 

I am going to do something like this myself, but just a suggestion.

**Comment by twostraws** [comment]
Hello! Yes, I see why this is important, but I'm not fully clear on why this isn't already solved by the existing `makeUniqueCopy()` method.

func createModifiedFireworks() -> VortexSystem {
    let modifiedFireworks = VortexSystem.fireworks.makeUniqueCopy()
    modifiedFireworks.position = [0.5, 0.5]
    return modifiedFireworks
}

**Comment by eoinnorris** [comment]
Right, missed that. Feel free to close this

**Comment by eoinnorris** [comment]
Actually I did!
